# Generated by Django 4.2.23 on 2026-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_alter_gamehuyhieu_loai_dieu_kien'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehuyhieu',
            name='diem_thuong',
            field=models.IntegerField(default=0, help_text='Số điểm nhận được khi đạt huy hiệu này', verbose_name='Điểm thưởng'),
        ),
    ]
