# Generated by Django 4.2.23 on 2026-02-28 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('TRIP_APPROVED', 'Chuyến đi được duyệt'), ('TRIP_REJECTED', 'Chuyến đi bị từ chối'), ('MEMBER_JOINED', 'Có người xin vào chuyến đi'), ('MEMBER_APPROVED', 'Được duyệt vào chuyến đi'), ('MEMBER_REJECTED', 'Bị từ chối khỏi chuyến đi'), ('TREK_APPROVED', 'Cung đường được duyệt'), ('TREK_REJECTED', 'Cung đường bị từ chối'), ('POST_APPROVED', 'Bài viết được duyệt'), ('POST_REJECTED', 'Bài viết bị từ chối'), ('NEW_COMMENT', 'Bình luận mới'), ('BADGE_EARNED', 'Nhận huy hiệu mới'), ('SYSTEM', 'Thông báo hệ thống')], default='SYSTEM', max_length=20, verbose_name='Loại')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(blank=True, default='', verbose_name='Nội dung')),
                ('lien_ket', models.CharField(blank=True, default='', max_length=500, verbose_name='Liên kết')),
                ('da_doc', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-ngay_tao'],
                'indexes': [models.Index(fields=['nguoi_nhan', '-ngay_tao'], name='notificatio_nguoi_n_fee4a9_idx'), models.Index(fields=['nguoi_nhan', 'da_doc'], name='notificatio_nguoi_n_cd4dbd_idx')],
            },
        ),
    ]
